backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - label: "Blog Posts"
    name: "posts"
    folder: "public/data/posts"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "string" }